// swift-tools-version:6.2
// Generated by scripts/lib_publish/publish-libraries.py. Do not edit by hand.
import PackageDescription

let package = Package(
    name: "moot-memory",
    platforms: [
        .macOS(.v26),
        .iOS(.v26),
    ],
    products: [
        .library(name: "CorpusKit", targets: ["CorpusKit"]),
        .library(name: "CorpusKitProviders", targets: ["CorpusKitProviders"]),
        .library(name: "LocusKit", targets: ["LocusKit"]),
        .library(name: "VectorKit", targets: ["VectorKit"])
    ],
    dependencies: [
        .package(url: "https://github.com/codedaptive/moot-core.git", exact: "1.0.29"),
        .package(url: "https://github.com/codedaptive/moot-semantics.git", exact: "1.0.29"),
        .package(url: "https://github.com/codedaptive/moot-system.git", exact: "1.0.29"),
        .package(url: "https://github.com/apple/swift-crypto.git", from: "4.0.0")
    ],
    targets: [
        .target(
            name: "CorpusKit",
            dependencies: [.product(name: "SubstrateTypes", package: "moot-core"), .product(name: "SubstrateLib", package: "moot-core"), .product(name: "SubstrateML", package: "moot-core"), .product(name: "EngramLib", package: "moot-core"), .product(name: "EideticLib", package: "moot-semantics"), .product(name: "IntellectusLib", package: "moot-core"), .product(name: "PersistenceKit", package: "moot-system"), .product(name: "PersistenceKitInMemory", package: "moot-system"), .product(name: "PersistenceKitSQLite", package: "moot-system"), .product(name: "ConvergenceKit", package: "moot-system"), "VectorKit", .product(name: "QueueKit", package: "moot-system"), .product(name: "Crypto", package: "swift-crypto")],
            path: "packages/kits/CorpusKit/Sources/CorpusKit"
        ),
        .target(
            name: "CorpusKitProviders",
            dependencies: ["CorpusKit", .product(name: "SubstrateTypes", package: "moot-core"), .product(name: "SubstrateKernel", package: "moot-core"), .product(name: "SubstrateML", package: "moot-core"), .product(name: "EngramLib", package: "moot-core"), "VectorKit", .product(name: "LatticeLib", package: "moot-semantics")],
            path: "packages/kits/CorpusKit/Sources/CorpusKitProviders"
        ),
        .testTarget(
            name: "CorpusKitTests",
            dependencies: ["CorpusKit", "CorpusKitProviders", "VectorKit", .product(name: "PersistenceKitInMemory", package: "moot-system"), .product(name: "PersistenceKitSQLite", package: "moot-system"), .product(name: "SubstrateTypes", package: "moot-core"), .product(name: "SubstrateLib", package: "moot-core"), .product(name: "IntellectusLib", package: "moot-core"), .product(name: "LatticeLib", package: "moot-semantics")],
            path: "packages/kits/CorpusKit/Tests/CorpusKitTests",
            resources: [.copy("../SharedVectors")]
        ),
        .target(
            name: "LocusKit",
            dependencies: [.product(name: "SubstrateLib", package: "moot-core"), .product(name: "SubstrateTypes", package: "moot-core"), .product(name: "SubstrateKernel", package: "moot-core"), .product(name: "SubstrateML", package: "moot-core"), .product(name: "PersistenceKit", package: "moot-system"), .product(name: "IntellectusLib", package: "moot-core"), .product(name: "LatticeLib", package: "moot-semantics")],
            path: "packages/kits/LocusKit/Sources/LocusKit"
        ),
        .testTarget(
            name: "LocusKitTests",
            dependencies: ["LocusKit", .product(name: "PersistenceKitSQLite", package: "moot-system"), .product(name: "PersistenceKitInMemory", package: "moot-system"), .product(name: "IntellectusLib", package: "moot-core")],
            path: "packages/kits/LocusKit/Tests/LocusKitTests"
        ),
        .target(
            name: "VectorKit",
            dependencies: [.product(name: "EngramLib", package: "moot-core"), .product(name: "SubstrateTypes", package: "moot-core"), .product(name: "SubstrateML", package: "moot-core"), .product(name: "PersistenceKit", package: "moot-system"), .product(name: "IntellectusLib", package: "moot-core")],
            path: "packages/kits/VectorKit/Sources/VectorKit"
        ),
        .testTarget(
            name: "VectorKitTests",
            dependencies: ["VectorKit", .product(name: "PersistenceKitInMemory", package: "moot-system"), .product(name: "PersistenceKitSQLite", package: "moot-system"), .product(name: "IntellectusLib", package: "moot-core")],
            path: "packages/kits/VectorKit/Tests/VectorKitTests"
        )
    ]
)
